---

- name: install Java 1.8
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Use Java 1.8 version 
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.48.amzn1.x86_64/jre/bin/java

- name: Update file with owner and permissions for logstash.repo
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'

- name: Install Elastic Search GPG Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install LogStash
  yum:
    name: logstash
    state: present

#- name: Backing up original logstash files just in case
#  archive:
#    path: /etc/logstash/
#    dest: /etc/logstash/logstash-orig-files.tgz

- name: Deploy Cesar's custom logstash configs
  copy:
    src:  logstash/
    dest: /etc/logstash/
    owner: root
    group: root
    mode: '0644'

# Major HACK!
# Fix me - this command doesn't cleanly run when executed via Ansible
# curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -
- name: Deploy the rbenv env
  copy:
    src:  rbenv/
    dest: /root/.rbenv/
    owner: root
    group: root
    mode: '0644'

- name: Update our PATH in preparation for the ruby env installer
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc

- name: Set our new PATH
  shell: source ~/.bashrc

- name: Download Ruby Env required by the logstash sysv installer
  shell: curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -

- name: Install Ruby 2.7.0
  shell: /root/.rbenv/bin/rbenv install 2.7.0

- name: Install Ruby 2.7.0
  shell: /root/.rbenv/bin/rbenv global 2.7.0

- name: Updating /etc/hosts as required by the logstash sysv5 installer
  shell: a=`curl http://169.254.169.254/latest/meta-data/local-ipv4` ; b=`curl http://169.254.169.254/latest/meta-data/hostname` ; echo $a $b >> /etc/hosts

- name: Enable SYSV Start Up Script for Logstash
  shell: /usr/share/logstash/bin/system-install /etc/logstash/startup.options sysv

- name: Add Logstash as a managed service
  shell: chkconfig --add logstash

- name: Start Logstash
  shell: /sbin/service logstart start
