---

- name: install Java 1.8
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Use Java 1.8 version 
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.48.amzn1.x86_64/jre/bin/java

- name: Update file with owner and permissions for logstash.repo
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'

- name: Install Elastic Search GPG Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install LogStash
  yum:
    name: logstash
    state: present

- name: Backing up original logstash files just in case
  archive:
    path: /etc/logstash
    dest: /etc/logstash/logstash-orig-files.tgz

- name: Update file with owner and permissions for logstash.repo
  copy:
    src:  logstash/*
    dest: /etc/logstash/
    owner: root
    group: root
    mode: '0644'

