---

- name: install Java 1.8
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Use Java 1.8 version 
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.48.amzn1.x86_64/jre/bin/java

- name: Update file with owner and permissions for logstash.repo
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: '0644'

- name: Install Elastic Search GPG Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install LogStash
  yum:
    name: logstash
    state: present


# Example checkout code from IA repo that contains logstash files
- git:
    repo: 'git@ghe.coxautoinc.com:ETS-IA/aws_logs_optimizer.git'
    dest: /tmp/aws_logs_optimizer.repo
    accept_hostkey: True
    #version: release-0.22
