---

- name: Ensure latest version of c10k server
  dnf:
    name: "{{ c10kserver_download_url['rpm'] }}"
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Ensure latest version of c10k server
  dnf:
    name: "{{ c10kserver_download_url['deb'] }}"
    state: latest
  when: ansible_os_family == 'Debian'

- name: Render service template
  template:
    src: systemd.j2
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: root
    group: root
    mode: 0644
  vars:
    program: "{{ item }}"
  with_items: "{{ c10kservers }}"
  changed_when: True
  notify:
    - systemd reload
    - systemd enable
